produto_1 = input('Digite o nome do produto 1: ')
preco_p1 = float(input('Digite o preço unitário do produto 1: '))
quantidade_p1 = int(input('Digite a quantidade do produto 1: '))
produto_2 = input('Digite o nome do produto 2: ')
preco_p2 = float(input('Digite o preço unitário do produto 2: '))
quantidade_p2 = int(input('Digite a quantidade do produto 2: '))
produto_3 = input('Digite o nome do produto 3: ')
preco_p3 = float(input('Digite o preço unitário do produto 3: '))
quantidade_p3 = int(input('Digite a quantidade do produto 3: '))
total = (preco_p1*quantidade_p1) + (preco_p2*quantidade_p2) + (preco_p3*quantidade_p3)
print(f"Total: R${total:,.2f}")